ID = "cnn-topstories"
Description = "CNN news feed / Top stories"
URL = "www.cnn.com"
ContentURL = "http://rss.cnn.com/rss/cnn_topstories.rss"
Processors = ["ExternalLinkRemover"]
Regions = ["US"]
Language = "en"
