ID = "nyt-space"
Description = "NYT Space and Technology"
URL = "www.nytimes.com"
ContentURL = "http://rss.nytimes.com/services/xml/rss/nyt/Space.xml"
Categories = ["Space", "Technology"]
Processors = ["ExternalLinkRemover"]
Language = "en"