ID = "welt-sport"
Description = "Welt Sport feed"
URL = "www.welt.de"
ContentURL = "https://www.welt.de/feeds/section/sport.rss"
Processors = ["ExternalLinkRemover"]
Language = "de"
Categories = ["Sports"]
