ID = "google-sports"
Description = "Google news feed"
URL = "www.google.com"
ContentURL = "https://news.google.com/?output=rss&topic=s"
Processors = ["ImageExtractor", "ExternalLinkRemover", "BoldElementRemover"]
Regions = ["US", "CA"]
Language = "en"